---
title: "Clustering LDA"
author: "Mairead Dillon"
date: '2022-11-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
library(tidyverse)
library(MASS)
library(ROCR)
library(caret)

# Load data
load("/Users/maireaddillon/Documents/Duke/BIOS-707/Project/Private707/data/Cluster Data/ClusterTrain.RData")
load("/Users/maireaddillon/Documents/Duke/BIOS-707/Project/Private707/data/Cluster Data/ClusterTest.RData")
```
   
```{r}
# Get rid of duplicate variable in dataset
Train <- ClusterTrain %>% subset(select = c(Clus1_physical,
                                            Clus2_physical,
                                            Clus1_social,
                                            Clus2_social,
                                            Clus1_psychological,
                                            Clus2_psychological,
                                            Clus1_demo,
                                            Clus2_demo,
                                            Clus1_school,
                                            Clus2_school))
Test <- ClusterTest %>% subset(select = c(Clus1_physical,
                                            Clus2_physical,
                                            Clus1_social,
                                            Clus2_social,
                                            Clus1_psychological,
                                            Clus2_psychological,
                                            Clus1_demo,
                                            Clus2_demo,
                                            Clus1_school,
                                            Clus2_school))

# Make data numeric
X_Train <- sapply(Train, as.numeric)
X_Test <- sapply(Test, as.numeric)

# Make dataframe
X_Train <- as.data.frame(X_Train)
X_Test <- as.data.frame(X_Test)

# Make vector with dependent variable
Y_Train <- ClusterTrain %>% subset(select = SelfPerceivedHealth)
Y_Test <- ClusterTest %>% subset(select = SelfPerceivedHealth)

# Standardize data
X_Train_Standardized <- scale(X_Train, center=TRUE, scale=TRUE)
X_Test_Standardized <- scale(X_Test, center=TRUE, scale=TRUE)

# Remerge data
Train_Standardized <- cbind(X_Train_Standardized, Y_Train)
Test_Standardized <- cbind(X_Test_Standardized, Y_Test)
```
     
```{r}
# Train linear discriminant analysis model
lda_model <- lda(SelfPerceivedHealth~., data=Train_Standardized)
lda_model

# Make predictions
predictions <- predict(lda_model, Test_Standardized)

# Model accuracy
mean(predictions$class==Test_Standardized$SelfPerceivedHealth)

# Plot histogram of LDA
predictions_training <- predict(lda_model, Train_Standardized)
ldahist(data = predictions_training$x[,1], g=Train_Standardized$SelfPerceivedHealth)

# Plot
lda_plot_data <- cbind(Train_Standardized, predict(lda_model)$x)

# ggplot(lda_plot_data, aes(LD1, SelfPerceivedHealth)) + geom_point(aes(color = SelfPerceivedHealth))

ggplot(lda_plot_data, aes(x = 1:nrow(lda_plot_data), y = LD1)) +
  geom_point(aes(color=SelfPerceivedHealth))
```

