---
title: "Linear Discriminant Analysis"
author: "Mairead Dillon"
date: '2022-11-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
library(tidyverse)
library(MASS)
library(ROCR)
library(caret)

# Load data
load("/Users/maireaddillon/Documents/Duke/BIOS-707/Project/Private707/data/ModelDev_Train.RData")
load("/Users/maireaddillon/Documents/Duke/BIOS-707/Project/Private707/data/ModelDev_Test.RData")
load("/Users/maireaddillon/Documents/Duke/BIOS-707/Project/Private707/data/ValidationTest.RData")
```
   
   
```{r}
# Get rid of duplicate variable in datasets
Train1 <- Train %>% subset(select = -c(P28))
Test1 <- Test %>% subset(select = -c(P28))
Validation1 <- validation_test %>% subset(select = -c(P28))

# Make datasets with independent variables
X_Train <- Train1 %>% subset(select = -c(SelfPerceivedHealth))
X_Test <- Test1 %>% subset(select = -c(SelfPerceivedHealth))
X_Val <- Validation1 %>% subset(select = -c(SelfPerceivedHealth))

# Make data numeric
X_Train <- sapply(X_Train, as.numeric)
X_Test <- sapply(X_Test, as.numeric)
X_Val <- sapply(X_Val, as.numeric)

# Make dataframes
X_Train <- as.data.frame(X_Train)
X_Test <- as.data.frame(X_Test)
X_Val <- as.data.frame(X_Val)

# Make vectors with dependent variables
Y_Train <- Train1 %>% subset(select = SelfPerceivedHealth)
Y_Test <- Test1 %>% subset(select = SelfPerceivedHealth)
Y_Val <- Validation1 %>% subset(select = SelfPerceivedHealth)

# Standardize data
X_Train_Standardized <- scale(X_Train, center=TRUE, scale=TRUE)
X_Test_Standardized <- scale(X_Test, center=TRUE, scale=TRUE)
X_Val_Standardized <- scale(X_Val, center=TRUE, scale=TRUE)

# Remerge data
Train_Standardized <- cbind(X_Train_Standardized, Y_Train)
Test_Standardized <- cbind(X_Test_Standardized, Y_Test)
Validation_Standardized <- cbind(X_Val_Standardized, Y_Val)
```
   
    
```{r}
# Train linear discriminant analysis model
lda_model <- lda(SelfPerceivedHealth~., data=Train_Standardized)
lda_model
plot(lda_model)

# Make predictions on test data
predictions <- predict(lda_model, Test_Standardized)

# Make predictions on validation data (final test)
predictions_val <- predict(lda_model, Validation_Standardized)

# Model accuracy for test data
mean(predictions$class==Test_Standardized$SelfPerceivedHealth)

# Sensitivity for test data
sensitivity(Test_Standardized$SelfPerceivedHealth, predictions$class)

# Specificity for test data
specificity(Test_Standardized$SelfPerceivedHealth, predictions$class)

# Model accuracy for validation data (final test)
mean(predictions_val$class==Validation_Standardized$SelfPerceivedHealth)

# Sensitivity for validation data (final test)
sensitivity(Validation_Standardized$SelfPerceivedHealth, predictions_val$class)

# Specificity for validation data (final test)
specificity(Validation_Standardized$SelfPerceivedHealth, predictions_val$class)

# Plot histogram of LDA on test data
ldahist(data = predictions$x[,1], g=Train_Standardized$SelfPerceivedHealth)

# Plot histogram of LDA on validation data
ldahist(data = predictions_val$x[,1], g=Validation_Standardized$SelfPerceivedHealth)

# Save training data and predictions in dataframe for plot
lda_plot_data <- cbind(Train_Standardized, predict(lda_model)$x)

# Plot training data points against LD1
jpeg("LDA_GGPlot.jpg")
ggplot(lda_plot_data, aes(x = 1:nrow(lda_plot_data), y = LD1)) +
    geom_point(aes(color=SelfPerceivedHealth)) +
    xlab("Student Responses") +
    ggtitle("LDA Results") +
    theme_classic() +
    scale_color_discrete(name="Self Perceived Health",
                         labels=c("Good Health", "Poor Health"))
dev.off()
    scale_fill_brewer(labels=c(0,1), palette="Paired")
```
    
   
```{r}
## Test set
# Run prediction function
pred <- prediction(as.numeric(predictions$class), Test_Standardized$SelfPerceivedHealth)

# Run performance function
perf <- performance(pred, "tpr", "fpr")

# Plot ROC curve
plot(perf)

# Calculate area under the curve
auc.tmp <- performance(pred, "auc")
auc <- as.numeric(auc.tmp@y.values)
print(auc)
```
    
```{r}
## Validation set
# Run prediction function
pred_val <- prediction(as.numeric(predictions_val$class), Validation_Standardized$SelfPerceivedHealth)

# Run performance function
perf_val <- performance(pred_val, "sens", "spec")

# Plot ROC curve
plot(perf_val)

# Calculate area under the curve
auc.tmp <- performance(pred_val, "auc")
auc <- as.numeric(auc.tmp@y.values)
print(auc)

# Plot and save ROC curve with AUC on plot
jpeg("LDA_ROC_Curve.jpg")
plot(perf_val,
     main="ROC Curve")
text(0.4, 0.6, "AUC=0.722")
dev.off()
```
    




