---
title: "Clustering"
output: html_document
date: "2022-11-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(patchwork)
library(gridExtra)
library(psych)
library(corrplot)
library(ggfortify)
library(factoextra)
library(readr)
library(gmodels)
library(DataExplorer)
library(fclust)
```



```{r}
setwd("/Users/sdm98/Documents/GitHub/707FinalProject")
load("/Users/sdm98/Documents/GitHub/Private707/data/ModelDev_Train.RData")

#change back to numeric
col_names <- names(Train)
Train[,col_names] <- lapply(Train[,col_names] , as.numeric)

#Standardize
#remove outcome (SelfPerceivedHealth) and standardize all other variables
Train_standardized <- Train %>% subset(select = -c(SelfPerceivedHealth, P28)) %>% mutate_all(~(scale(.) %>% as.vector))
#summary(Train_standardized)

#Perform hierarchical clustering on entire data set - not informative of self-perceived health (no surprise)
#dis <- dist(Train_standardized, method = "euclidean")
#clus1 <- hclust(dis, method = "complete")

#plot(clus1)
#table(cutree(clus1, k=2), Train$SelfPerceivedHealth)

#Perform clustering on specific groups of variables and label clusters by self-perceived health
```


```{r}

#Physical Health Related
phys_health <- Train_standardized %>% 
  subset(select = c(#miss school for sickness
                    P14ab1, 
                    
                    #doctor's appt
                    P14ab2, 
                    
                    #not enough sleep
                    P14ab5, 
                    
                    #sports team/physical activity
                    P26a, P26f, 
                    
                    #dentist appt
                    P30, 
                    
                    #physical disability/long term health problem
                    P33, 
                    
                    #physical activity
                    P37, 
                    
                    #skipping lunch
                    P39a,
                    
                    #fast food, soda, sports drinks, energy drinks,
                    P40d, P41b, P41c, P41d, 
                    
                    #sweetened coffee/tea, water
                    P41e, P41g,
                    
                    #asthma, allergy w/ epi pen, hours of sleep/nigh
                    P42c, P42d, P45, 
                    
                    #vape, alcohol, alcohol quantity, prescription drugs
                    P71d, P74, P76, P81,
                    
                    FiveFV, Binge, Diab_Prediab,
                    DrugFreq, NicFreq, DentalIssues))


start_time <- Sys.time()


phys_health_clus <- FKM(phys_health, 
                        k = 2, 
                        m = 1.2, #fuzziness
                        RS = 10)#number of random starts

end_time <- Sys.time()
end_time - start_time

#Compare with fruit/vegetable consumption
table(phys_health_clus$clus[,1], Train$FiveFV)

#Compare with Diab/Prediab
table(phys_health_clus$clus[,1], Train$Diab_Prediab)

#Compare with long term disability
table(phys_health_clus$clus[,1], Train$P33)

#No clear cluster relationship for good/bad physical health


#compare with self-perceived health 1 = good 2 = bad
table(phys_health_clus$clus[,1], Train$SelfPerceivedHealth)

phys_crosstab <- CrossTable(phys_health_clus$clus[,1], Train$SelfPerceivedHealth, prop.chisq = FALSE)
phys_prop <- 100*phys_crosstab$prop.col
  #9182 were misclassified 

      phys_binary <- ggplot(phys_prop, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Physical Health Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      phys_crosstab_5 <- CrossTable(phys_health_clus$clus[,1], Train$P28, prop.chisq = FALSE)
      phys_prop_5 <- 100*phys_crosstab_5$prop.col
      
      
      phys_5 <- ggplot(phys_prop_5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Physical Health Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      
      grid.arrange(phys_binary, phys_5, nrow = 1, ncol = 2)


```


```{r}

#Psychological Health Related
psych_health <- Train_standardized %>%
  subset(select = c(P14ab4, P14ab11, P27f, P34, 
                    
                    #not sure if 49 should be included
                    P49a, P49c, P49e,
                    P49f, P49g, P49h, P49i, P49j, P49k, P49l, 
                    P49n, 
                    
                    P50a, P50b, P50c, P50d, 
                    
                    #not sure if 70 should be included
                    P70d, 
                    
                    P86, AlcDrug_Residence, ImprisGaurd, 
                    MentalHealthSelf, AlcDrugSelf, Suicide))

psych_health_clus <- FKM(psych_health, 
                        k = 2, 
                        m = 1.2, #fuzziness
                        RS = 10)#number of random starts

#Compare with suicide attempt/consider 
table(psych_health_clus$clus[,1], Train$Suicide)

#Compare with feeling nervous/anxious/on edge 1 = not at all, 4 = nearly every day
table(psych_health_clus$clus[,1], Train$P50c)
  #this suggests cluster 1 = good psychological health, cluster 2 = bad psychological health

#compare cluster membership to self-perceived health
table(psych_health_clus$clus[,1], Train$SelfPerceivedHealth)
  #2 = good, 1 = bad?
  #7652 misclassified

      psych_crosstab <- CrossTable(psych_health_clus$clus[,1], Train$SelfPerceivedHealth, prop.chisq = FALSE)
      psych_prop <- 100*psych_crosstab$prop.col
      
      
      psych_binary <- ggplot(psych_prop, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Psychological Health Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      psych_crosstab_5 <- CrossTable(psych_health_clus$clus[,1], Train$P28, prop.chisq = FALSE)
      psych_prop_5 <- 100*psych_crosstab_5$prop.col
      
      
      psych_5 <- ggplot(psych_prop_5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Psychological Health Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      grid.arrange(psych_binary, psych_5, nrow = 1, ncol = 2)

```



```{r}
#Social Support Related
social <- Train_standardized %>%
  subset(select = c(P14ab6, P14ab7, P14ab9, P18b, 
                    P18c, P18d, 
                    
                    #bullying
                    P20a, P20b, P20c, P20f, P20g, P20h,
                    P21, P22a, P22e, P23c, P23e, 
                    
                    #school/community programs
                    P25, P26b, P26d, P26e, P26g, P26h,
                    
                    #leadership, trusting relationships, 
                    #decision making, learning useful skills
                    P27b, P27c, P27e, P27g, 
                    
                    #feel cared about
                    P47a, P47b, P47c, P47d, P47e, P49d,
                    
                    #not sure about these
                    P49m, P49o, P49p, P49q,
                    
                    #unhealthy/abusive home life
                    P61, P62, P63, P64, P65, P66,
                    
                    #run away from home, hit others
                    P70a, P70c,
                    
                    #romantic relationship abuse
                    AbuseRelationship
                
                   ))

social_clus <- FKM(social, 
                  k = 2, 
                  m = 1.2, #fuzziness
                  RS = 10)#number of random starts

table(social_clus$clus[,1], Train$SelfPerceivedHealth)
  #8246 misclassified

#compare cluster to 'I feel safe at home' 1 = strongly agree, 4 = strongly disagree
table(social_clus$clus[,1], Train$P18d)
#compare cluster to 'How much do you feel your parents care about you' 1 = not at all, 5 = very much
table(social_clus$clus[,1], Train$P47a)

#this may suggest cluster 2 = bad social support and cluster 1 = good social support

      
      social_crosstab <- CrossTable(social_clus$clus[,1], Train$SelfPerceivedHealth, prop.chisq = FALSE)
      social_prop <- 100*social_crosstab$prop.col
      
      
      soc_binary <- ggplot(social_prop, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Social Support Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(2, 1))
      
      social_crosstab_5 <- CrossTable(social_clus$clus[,1], Train$P28, prop.chisq = FALSE)
      social_prop_5 <- 100*social_crosstab_5$prop.col
      
      
      soc_5 <- ggplot(social_prop_5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Social Support Cluster in Self-Perceived Health Groups") + 
        scale_fill_brewer(labels = c('Good Health','Bad Health'), palette = 'Set2', limits = c(2, 1))
      
      
      grid.arrange(soc_binary, soc_5, nrow = 1, ncol = 2)
```



```{r}
#School Related
school <- Train_standardized %>%
  subset(select = c(P8, P11, P13, P14a, 
                    P14ab12, P14ab13, P14ab14, P15, 
                    P16a, P16b, P16c, P17a, P17b, P17c,
                    P26c
                   ))

school_clus <- FKM(school, 
                        k = 2, 
                        m = 1.2, #fuzziness
                        RS = 10)#number of random starts

table(school_clus$clus[,1], Train$SelfPerceivedHealth)
  #9847 misclassified

      
      school_crosstab <- CrossTable(school_clus$clus[,1], Train$SelfPerceivedHealth, prop.chisq = FALSE)
      school_prop <- 100*school_crosstab$prop.col
      
      
      sch_binary <- ggplot(school_prop, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each School Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(2, 1))
      
      school_crosstab_5 <- CrossTable(school_clus$clus[,1], Train$P28, prop.chisq = FALSE)
      school_prop_5 <- 100*school_crosstab_5$prop.col
      
      
      sch_5 <- ggplot(school_prop_5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each School Cluster in Self-Perceived Health Groups") + 
        scale_fill_brewer(labels = c('Good Health','Bad Health'), palette = 'Set2', limits = c(2, 1))
      
      
      grid.arrange(sch_binary, sch_5, nrow = 1, ncol = 2)
```

```{r}
#School Related
demo <- Train_standardized %>%
  subset(select = c(P1, P2, Biosex, P5, P12,
                    P14ab3, P14ab8, P14ab10,
                    P38, FosterCare
                   ))

demo_clus <- FKM(demo, 
                  k = 2, 
                  m = 1.2, #fuzziness
                  RS = 10)#number of random starts

table(demo_clus$clus[,1], Train$SelfPerceivedHealth)
  #12082 misclassified



      
      demo_crosstab <- CrossTable(demo_clus$clus[,1], Train$SelfPerceivedHealth, prop.chisq = FALSE)
      demo_prop <- 100*demo_crosstab$prop.col
      
      
      demo_binary <- ggplot(demo_prop, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Demographic Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      demo_crosstab_5 <- CrossTable(demo_clus$clus[,1], Train$P28, prop.chisq = FALSE)
      demo_prop_5 <- 100*demo_crosstab_5$prop.col
      
      
      demo_5 <- ggplot(demo_prop_5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Demographic Cluster in Self-Perceived Health Groups") + 
        scale_fill_brewer(labels = c('Good Health','Bad Health'), palette = 'Set2', limits = c(1, 2))
      
      
      grid.arrange(demo_binary, demo_5, nrow = 1, ncol = 2)
```


```{r}
#run all together

subset <- as.data.frame(c(social, psych_health, phys_health, school, demo))
subset_clus <- FKM(subset, 
                        k = 2, 
                        m = 1.2, #fuzziness
                        RS = 10)#number of random starts

table(subset_clus$clus[,1], Train$SelfPerceivedHealth)
  #7668 misclassified 

      subset_crosstab <- CrossTable(subset_clus$clus[,1], Train$SelfPerceivedHealth, prop.chisq = FALSE)
      propcol <- 100*subset_crosstab$prop.col
      
      
      subset_binary <- ggplot(propcol, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Subset Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      
      subset_crosstab_5 <- CrossTable(subset_clus$clus[,1], Train$P28, prop.chisq = FALSE)
      subset_prop_5 <- 100*subset_crosstab_5$prop.col
      
      
      subset_5 <- ggplot(subset_prop_5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Subset Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2', limits = c(1, 2))
      
      
      grid.arrange(subset_binary, subset_5, nrow = 1, ncol = 2)




```



```{r}
#Learn  about misclassified for each group
#poor self-perceived health
poorind <- which(Train$SelfPerceivedHealth == 2,)
poorself <- subset[poorind,]
poorself_clust <- (as.data.frame(subset_clus$clus[,1]))[poorind,]

misspoor <- poorself[Train$SelfPerceivedHealth[poorind] != poorself_clust,]
samepoor <- poorself[Train$SelfPerceivedHealth[poorind] == poorself_clust,]

summary(colMeans(misspoor) - colMeans(samepoor))
sum(abs(colMeans(misspoor) - colMeans(samepoor)) > 1)

data.frame(diff = abs(colMeans(misspoor) - colMeans(samepoor))) %>% filter(diff > 1)

#good self-perceived health
goodind <- which(Train$SelfPerceivedHealth == 1,)
goodself <- subset[goodind,]
goodself_clust <- (as.data.frame(subset_clus$clus[,1]))[goodind,]

missgood <- goodself[Train$SelfPerceivedHealth[goodind] != goodself_clust,]
samegood <- goodself[Train$SelfPerceivedHealth[goodind] == goodself_clust,]

summary(colMeans(missgood) - colMeans(samegood))
sum(abs(colMeans(missgood) - colMeans(samegood)) > 1.01)

data.frame(diff = abs(colMeans(missgood) - colMeans(samegood))) %>% filter(diff > 1.01)
```

```{r}
#Good Self-Perceived Health: Those who were classified correctly were more likely to respond 'Very much" to P47a, 'How much do you feel your parents care about you?'

P47a_missgood <-  missgood %>% group_by(P47a) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47a, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P47a where SelfPerceivedHealth = 1")

P47a_samegood <-  samegood %>% group_by(P47a) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47a, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P47a where SelfPerceivedHealth = 1")

grid.arrange(P47a_missgood, P47a_samegood, nrow = 1, ncol = 2)

#Poor Self-Perceived Health: Those who were classified correctly were less likely to respond 'Very much" to P47a, 'How much do you feel your parents care about you?'

P47a_misspoor <-  misspoor %>% group_by(P47a) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47a, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P47a where SelfPerceivedHealth = 2")

P47a_samepoor <-  samepoor %>% group_by(P47a) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47a, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P47a where SelfPerceivedHealth = 2")

grid.arrange(P47a_misspoor, P47a_samepoor, nrow = 1, ncol = 2)

```

```{r}
#Good Self-Perceived Health: Those who were classified correctly were more likely to respond 'Very much" to P47b, 'How much do you feel other adult relatives care about you?'

P47b_missgood <-  missgood %>% group_by(P47b) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47b, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P47a where SelfPerceivedHealth = 1")

P47b_samegood <-  samegood %>% group_by(P47b) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47b, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P47a where SelfPerceivedHealth = 1")

grid.arrange(P47b_missgood, P47b_samegood, nrow = 1, ncol = 2)

#Poor Self-Perceived Health: Those who were classified correctly were less likely to respond 'Very much" to P47b, 'How much do you feel other adult relatives care about you?'

P47b_misspoor <-  misspoor %>% group_by(P47b) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47b, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P47b where SelfPerceivedHealth = 2")

P47b_samepoor <-  samepoor %>% group_by(P47b) %>% summarise(n=n())%>%
  ggplot(., aes(x = P47b, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P47b where SelfPerceivedHealth = 2")

grid.arrange(P47b_misspoor, P47b_samepoor, nrow = 1, ncol = 2)

```

```{r}
#Good Self-Perceived Health: Those who were classified correctly were more likely to respond 'Extremely or almost always' to P49f, 'I feel good about my future.'

P49f_missgood <-  missgood %>% group_by(P49f) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49f, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P49f where SelfPerceivedHealth = 1")

P49f_samegood <-  samegood %>% group_by(P49f) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49f, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P49f where SelfPerceivedHealth = 1")

grid.arrange(P49f_missgood, P49f_samegood, nrow = 1, ncol = 2)

#Poor Self-Perceived Health: Those who were classified correctly were less likely to respond 'Extremely or almost always' to P49f, 'I feel good about my future.'

P49f_misspoor <-  misspoor %>% group_by(P49f) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49f, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P49f where SelfPerceivedHealth = 2")

P49f_samepoor <-  samepoor %>% group_by(P49f) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49f, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P49f where SelfPerceivedHealth = 2")

grid.arrange(P49f_misspoor, P49f_samepoor, nrow = 1, ncol = 2)

```

```{r}
#Good Self-Perceived Health: Those who were classified correctly were more likely to respond 'Extremely or almost always' to P49l, 'I feel valued and appreciated by others.'

P49l_missgood <-  missgood %>% group_by(P49l) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49l, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P49l where SelfPerceivedHealth = 1")

P49l_samegood <-  samegood %>% group_by(P49l) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49l, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P49l where SelfPerceivedHealth = 1")

grid.arrange(P49l_missgood, P49l_samegood, nrow = 1, ncol = 2)

#Poor Self-Perceived Health: Those who were classified correctly were less likely to respond 'Extremely or almost always' to P49l, 'I feel values and appreciated by others.'

P49l_misspoor <-  misspoor %>% group_by(P49l) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49l, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Misclassified Responses to P49l where SelfPerceivedHealth = 2")

P49l_samepoor <-  samepoor %>% group_by(P49l) %>% summarise(n=n())%>%
  ggplot(., aes(x = P49l, y = n))+
  geom_col(stat = "identity")+
  ggtitle(label = "Correctly Classified Responses to P49l where SelfPerceivedHealth = 2")

grid.arrange(P49l_misspoor, P49l_samepoor, nrow = 1, ncol = 2)

```



```{r}
#see what happens with 5 clusters
subset_clus5 <- kmeans(subset, centers = 5, nstart = 10)
table(subset_clus5$cluster, Train$SelfPerceivedHealth)
fviz_cluster(subset_clus5, psych_health, geom = 'point', main = 'Clusters with combination of categories')

      subset_crosstab5 <- CrossTable(subset_clus5$cluster, Train$SelfPerceivedHealth, prop.chisq = FALSE)
      propcol5 <- 100*subset_crosstab5$prop.col
      
      
      subset_binary5 <- ggplot(propcol5, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Subset Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2')
      
      
      subset_crosstab_55 <- CrossTable(subset_clus5$cluster, Train$P28, prop.chisq = FALSE)
      subset_prop_55 <- 100*subset_crosstab_55$prop.col
      
      
      subset_55 <- ggplot(subset_prop_55, aes(x = y, y = Freq, fill = x))+
        geom_bar(stat = "identity")+
        coord_flip()+
        labs(x = "Self-Perceived Health", y = "Percentage",fill = "Cluster")+
        ggtitle(label = "Proportion of Each Subset Cluster in Self-Perceived Health Groups")+ 
        scale_fill_brewer(labels = c('Good Health','Bad Health'),palette = 'Set2')
      
      
      grid.arrange(subset_binary5, subset_55, nrow = 1, ncol = 2)

```

